### ISSUE TITLE
Remove futile wc -l|awk '{print $1}'

### ISSUE THREAD

**Issue by xrat** [rcmdnk/sentaku#4]
If I am not mistaken, all commonly used versions of `wc` return only the line count if used as `wc -l < data`. So, the `awk` in
```
_s_ext_row=$(printf "%s\n" "${_s_header}"|wc -l|awk '{print $1}')
```
would be futile, then.
Actually, since you are using Bash you don't even need the `wc -l`:
```
readarray -t array <<<"${_s_header}"; $linecount=${#array[@]}
```
This does not count the `\n` included as string in `$_s_header`. You could use `printf -v var "%b"` to intrepret them, though. E.g., 
```
printf -v _s_header "%b\n" "${_s_header}"
```
I didn't test this thoroughly, but it should work.

**Comment by rcmdnk** [comment]
About `wc` command, you are right.

I think I used `awk` because it is used for where lines of a file is counted,
or where I want to use the number as characters (because `wc` puts spaces before  the number).
But it is not necessary here.

About the counting, `readarray` is a good idea to reduce external command dependence.
(ksharrays is set to 0 in the script, then it is also valid for Zsh.)
I implemented it there.

In addition, I found a bug in the line counting, relating printf using "%s" in sentaku's header.
Related to this, it required an additional line to the header to make "Searh" line.

The bug was fixed and I make it to put additional line automatically if necessary.




I found a bug here.

As you noted in the last, printf doesn't recognize `\n` if `%s` is used.
Therefore, firstly, the line count command should be like:

    _s_ext_row=$(printf "%b\n" "${_s_header}"... # use %b instead of %s

There should be one more line to the header for "Search' mode.
Therefore, I put `\n`.

But it require an additional line break at the end of the header, because `wc` commands

**Comment by xrat** [comment]
Good job! I just gave v0.4.0 a small test run and it worked perfectly.

It's rather cosmetic here, and perhaps obvious to you. So, just for the sake of completeness:
```
_s_ext_row=$(($(readarray -t line_count <<<"${_s_header}";
                  echo ${#line_count[@]})+1))
```
You could avoid calling a subshell, for instance, like this
```
readarray -t line_count <<<"${_s_header}"
_s_ext_row=$(( ${#line_count[@]}+1 ))
```

**Comment by rcmdnk** [comment]
I wrote like that because I would put them in one line.
I also realised that I can drop `local` definition line for line_count if it is only in `$()`. (then dropped it.)

**Comment by rcmdnk** [comment]
I realized that `readarray` is bash only command, so that I changed to use `wc`.

**Comment by xrat** [comment]
> I realized that readarray is bash only command

Sorry about that. I saw `#!/usr/bin/env bash` and didn't think about zsh or others.

**Comment by rcmdnk** [comment]
It uses bash if it run stand alone.
On the other hand, `sentaku` can be used as a library.
In this case, the script can be zsh, so that I want to keep the compatibility .
